name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Files for Deployment
        run: |
          cp index.html $GITHUB_WORKSPACE
          cp invoice.html $GITHUB_WORKSPACE
          cp .htaccess $GITHUB_WORKSPACE
          cp .htpasswd $GITHUB_WORKSPACE

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: $GITHUB_WORKSPACE
