name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Files
        run: ls -la   # Add a step to list directory contents for debugging

      - name: Copy Files for Deployment
        run: |
          if [[ ! -f "$GITHUB_WORKSPACE/invoice.html" ]]; then
            echo "Copying invoice.html"
            cp invoice.html $GITHUB_WORKSPACE
          else
            echo "invoice.html already exists in $GITHUB_WORKSPACE"
          fi

          if [[ ! -f "$GITHUB_WORKSPACE/.htaccess" ]]; then
            echo "Copying .htaccess"
            cp .htaccess $GITHUB_WORKSPACE
          else
            echo ".htaccess already exists in $GITHUB_WORKSPACE"
          fi

          if [[ ! -f "$GITHUB_WORKSPACE/.htpasswd" ]]; then
            echo "Copying .htpasswd"
            cp .htpasswd $GITHUB_WORKSPACE
          else
            echo ".htpasswd already exists in $GITHUB_WORKSPACE"
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: $GITHUB_WORKSPACE
          publish_branch: gh-pages
